"""Reward code generated by the LLM / AI agent.

This file is executed by ``main.py`` inside a sandbox namespace that exposes
the reward functions (see README.md): reset_reward, set_torso_targets,
set_feet_pos_parameters, set_feet_stepping_parameters, execute_plan.
Only numpy may be imported.

Task: walk forward at ~0.5 m/s with an alternating stepping gait.
"""

import numpy as np

reset_reward()
# 站立高度 1.28m，竖直，速度目标 (前进 0.5 m/s, 侧向 0)，不转向
set_torso_targets(1.28, 0.0, 0.0, 0.0, (0.5, 0.0), 0.0)
# 双脚贴地（步态由 stepping 参数驱动，不用静态抬脚）
set_feet_pos_parameters("left_foot", 0.0)
set_feet_pos_parameters("right_foot", 0.0)
# 动态步态：两只脚以 1.0 Hz 交替迈步（相位差 0.5），抬脚 0.1m、前伸 0.15m
set_feet_stepping_parameters("left_foot", 1.0, 0.5, 0.0, 0.15, 0.2, True)
set_feet_stepping_parameters("right_foot", 1.0, 0.5, 0.5, 0.15, 0.2, True)
execute_plan(5)
