"""Reward code generated by the LLM / AI agent.

This file is executed by ``main.py`` inside a sandbox namespace that exposes
exactly four functions (see README.md): reset_reward, set_torso_targets,
set_feet_pos_parameters, execute_plan. Only numpy may be imported.

Default content: stand upright and turn to face north (left, +90 degrees).
"""

import numpy as np

reset_reward()
set_torso_targets(1.28, 0.0, 0.0, np.deg2rad(90))
set_feet_pos_parameters("left_foot", 0.0)
set_feet_pos_parameters("right_foot", 0.0)
execute_plan(5)
